### ISSUE TITLE
ptreleases.cgi

### ISSUE THREAD

**Issue by ldraw-org** [ldraw-org/ldraworg-library#21]
Restore this page as it is used by LDView and possibly other programs.

**Comment by ldraw-org** [comment]
Implemented basic functionality. Advanced option will be provided if needed.

**Comment by tcobbs** [comment]
@ldraw-org The (http) download links generated by ptreleases.cgi don't work. For example:

http://library.ldraw.org/library/updates/lcad2302.zip
http://library.ldraw.org/library/updates/complete.zip

Changing the URLs from http to https allows them to work, but that wouldn't be supported by LDView.

**Comment by ldraw-org** [comment]
@tcobbs The entire /library/updates url tree is now opened to non-secure urls.

**Comment by tcobbs-bentley** [comment]
@ldraw-org Yesterday when I made my last comment, ptreleases.cgi worked via http. Today, after whatever changes you made to support http downloads of the library and updates, ptreleases.cgi redirects to https. So LDView's library update still doesn't work.

**Comment by ldraw-org** [comment]
@tcobbs This is also fixed

**Comment by ldraw-org** [comment]
@tcobbs BTW, when you patch LDView, the correct URL is:
library.ldraw.org/updates?output=<TAB|XML>
I can also make an API URL that returns JSON if that's easier.

**Comment by tcobbs-bentley** [comment]
I can update to the new URL for the next release.

However, the new script now appears to be ignoring the fields= URL parameter. LDView currently uses the following URL:

http://www.ldraw.org/cgi-bin/ptreleases.cgi?output=TAB&fields=type-format-date-url-size

It expects each line to contain tab separated fields in the order of type, then format, then date, then URL, then size. Since the fields parameter is ignored, it cannot parse the result. The result I get appears to be type, then name (like 1997-16), then date, then format, then URL, then size, then checksum. I can update LDView to deal with this, but old versions of LDView will never work with this response from the server.

**Comment by tcobbs-bentley** [comment]
Addendum to the above: I'm guessing that even if I got the right fields, existing LDView releases won't work since the download will be corrupted by my broken chunked downloading code, so if you feel that adding support for the fields= parameter to the new script is too much work, let me know.

**Comment by ldraw-org** [comment]
I can add support no problem. I'd like to have functionality if and when I can figure out how to serve gzipped files unchunked.

**Comment by tcobbs-bentley** [comment]
I'll update the next version not to include the tabs param, which will work with your current script. However, if you can get unchunked gzip working, that would be very nice so that older versions of LDView work again.

**Comment by ldraw-org** [comment]
Reopening to track investigation into non-chunked gzip transfers

**Comment by tcobbs** [comment]
I released LDView 4.5 today, and it works with the current ldraw.org server settings. TYI, in this release I updated the parts releases URL to `http://library.ldraw.org/updates?output=TAB`, but I did not update the unofficial parts check base URL of `http://www.ldraw.org/library/unofficial`.
