### ISSUE TITLE
Preview is distorted on mobile

### ISSUE THREAD

**Issue by SwampKryakwa** [ldraw-org/ldraworg-library#46]
For some reason preview appears vertically stretched on the mobile
![Screenshot_2023-01-11-19-12-41-559_com yandex browser](https://user-images.githubusercontent.com/87991018/211860154-9936d7d8-f4c7-40a9-a349-ce0fb30cdcd1.jpg)

**Comment by ldraw-org** [comment]
Do you have the same problem on the live Parts Tracker?

**Comment by SwampKryakwa** [comment]
No, it appears totally fine

**Comment by ldraw-org** [comment]
Ok. This is probably a bug. I'll check.

**Comment by ldraw-org** [comment]
I've confirmed the problem occurs with Android Chrome. I can't recreate the problem on any other browser including Chrome iOS and Windows. Since the problem doesn't exist on the live PT (I've confirmed that as well) a fix will have to wait until I reimplement the mobile menu scheme (which is the only real different in the markup between the two PT versions) to see if the problem persists.

**Comment by SwampKryakwa** [comment]
Chrome on iOS uses WebKit instead of chromium, which is very likely to be the reason of this difference

**Comment by ldraw-org** [comment]
This appears to be an Android only problem. I tested on Firefox as well as Google Chrome (Yandex isn't playing with my Android emulator for some reason). Again, once the HTML for mobile menu is restored, this may fix the bug.

**Comment by ldraw-org** [comment]
Now that the main menu isn't breaking formatting on mobile, this issue appears to be fixed.
